---
title: "12-ind-vars"
author: "Katrina Tsun"
date: "7/8/2020"
output: html_document
---

```{r}
library(tidyverse)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Lists of individual relevant variables
```{r parent}

add_parent_health <- function(df){
  # df : joined waves input
  # return : new data frame including additional variable about parental health insurance
  # works assuming each person has only 1 type of health insurance
  # drop unnecessary columns?
  df %>% 
    mutate(p_health = case_when(
      (PC21_1 == 1)&(PC21_2 != 1)&(PC21_3 != 1)&(PC21_4 != 1)&(PC21_5 != 1)&(PC21_6 != 1)&(PC21_7 != 1) ~ 1,
      (PC21_1 != 1)&(PC21_2 == 1)&(PC21_3 != 1)&(PC21_4 != 1)&(PC21_5 != 1)&(PC21_6 != 1)&(PC21_7 != 1) ~ 2,
      (PC21_1 != 1)&(PC21_2 != 1)&(PC21_3 == 1)&(PC21_4 != 1)&(PC21_5 != 1)&(PC21_6 != 1)&(PC21_7 != 1) ~ 3,
      (PC21_1 != 1)&(PC21_2 != 1)&(PC21_3 != 1)&(PC21_4 == 1)&(PC21_5 != 1)&(PC21_6 != 1)&(PC21_7 != 1) ~ 4,
      (PC21_1 != 1)&(PC21_2 != 1)&(PC21_3 != 1)&(PC21_4 != 1)&(PC21_5 == 1)&(PC21_6 != 1)&(PC21_7 != 1) ~ 5,
      (PC21_1 != 1)&(PC21_2 != 1)&(PC21_3 != 1)&(PC21_4 != 1)&(PC21_5 != 1)&(PC21_6 == 1)&(PC21_7 != 1) ~ 6,
      (PC21_1 != 1)&(PC21_2 != 1)&(PC21_3 != 1)&(PC21_4 != 1)&(PC21_5 != 1)&(PC21_6 != 1)&(PC21_7 == 1) ~ 7,
      (PC21_1 != 1)&(PC21_2 != 1)&(PC21_3 != 1)&(PC21_4 != 1)&(PC21_5 != 1)&(PC21_6 != 1)&(PC21_7 != 1) ~ 0,
      TRUE ~ 9999)
    )
}

parent_vars <- c("pc21_1", "pc21_2", "pc21_3", "pc21_4", "pc21_5", "pc21_6", "pc21_7", "PA10", "PA61", "PA62", "PA21", "PA55", "PA12", "PB8", "PA56", "PC31")


```

```{r wave 1}
w1_health <- c("h1to3", "h1to7", "h1gh1")

w1_social <- c("h1pf35", "h1pf36", "h1da7", "h1ed19", "h1ed20", "h1ed22", "h1fs13", "h1pr1", "h1pr2", "h1pr4", "h1nb3")

w1_peer <- c("h1su4", "h1su6", "h1su5", "h1su7")

w1_religion <- c("h1re3", "h1re4", "h1re7")

w1_family <- c("h1wp9", "h1wp10", "h1wp13", "h1wp14", "h1wp17f", "h1wp18f", "h1pf1", "h1pf4", "h1pf5", "h1pf23", "h1pf25", "h1pf24", "h1nm12f", "h1nm14", "h1nf12f", "h1nf14", "h1pr3", "h1pr5", "h1pr7", "h1pr8", "h1wp11", "h1wp12", "h1wp15", "h1wp16")

w1_parent_ses <- c("h1nf4", "h1nm4", "h1rf1", "h1rm1") 

w1_education <- c("h1gi20", "h1ee1", "h1ee2")

w1_prospects <- ("s45f")

w1_ses <- c(w1_parent_ses, w1_education, w1_prospects)

w1_ind_vars <- c(w1_health, w1_social, w1_peer, w1_religion, w1_family, w1_ses)
```

```{r wave 3}

w3_health <- c("h3to4", "h3to10", "h3gh18", "h3gh1", "h3hs1")

w3_social <- ("h3da15")

w3_prosocial <- c("h3cc6", "h3cc7", "h3cc8", "h3cc3")

w3_peer <- c("h3to133", "h3to135", "h3to136", "h3to134")

w3_religion <- c("h3re24", "h3re30", "h3re25", "h3re33", "h3re34")

add_w3_family<- function(df) {
  #df : joined waves input
  #return : new data frame with constructed family variables
  #combines variables by prioritizing first variable in list to create the following:
  #close_mother combines "h3wp20", "h3wp32", "h3wp46", "h3wp64"
  #close_father combines "h3wp25", "h3wp39", "h3wp53"
  #mother_support combines "h3wp21", "h3wp33", "h3wp47"
  #mother_support2 combines "h3wp22", "h3wp34", "h3wp48"
  #father_support combines "h3wp26", "h3wp40", "h3wp54"
  #father_support2 combines "h3wp27", "h3wp41", "h3wp55"
  #mother_warmth combines "h3wp19", "h3wp31", "h3wp45", "h3wp63"
  #father_warmth combines "h3wp24", "h3wp38", "h3wp52"
  
  #takes average of all answers, excluding NAs 
  #sibling_closeness combines "h3ws5a", "h3ws5b", "h3ws5c", "h3ws5d"
  #sibling_support combines "h3ws6a", "h3ws6b", "h3ws6c", "h3ws6d"
  
  #list of valid values 
  
  valid_vars <- c(1,2,3,4,5)
  support <- c(0,1)
  support2 <- c(1,2,3,4)
  sibling_valid <- c(0,1,2,3,4)
  
  df<- df %>% 
    mutate(close_father = case_when(h3wp25 %in% valid_vars ~ h3wp25,
                                     h3wp39 %in% valid_vars & !(h3wp25 %in% valid_vars) ~ h3wp39,
                                     !(h3wp39 %in% valid_vars) & !(h3wp25 %in% valid_vars) & (h3wp53 %in% valid_vars) ~ h3wp53,
                                     TRUE ~ 9999),
           close_mother = case_when(h3wp20 %in% valid_vars ~ h3wp20,
                                     h3wp32 %in% valid_vars & !(h3wp20 %in% valid_vars) ~ h3wp32,
                                     !(h3wp32 %in% valid_vars) & !(h3wp20 %in% valid_vars) & (h3wp46 %in% valid_vars) ~ h3wp46,
                                     !(h3wp32 %in% valid_vars) & !(h3wp20 %in% valid_vars) & !(h3wp46 %in% valid_vars) & (h3wp64 %in% valid_vars) ~ h3wp64,
                                     TRUE ~ 9999),
           mother_support = case_when(h3wp21 %in% support ~ h3wp21,
                                     h3wp33 %in% support & !(h3wp21 %in% support) ~ h3wp33,
                                     !(h3wp33 %in% support) & !(h3wp21 %in% support) & (h3wp47 %in% support) ~ h3wp47,
                                     TRUE ~ 9999),
           mother_support2 = case_when(h3wp22 %in% support2 ~ h3wp22,
                                     h3wp34 %in% support2 & !(h3wp22 %in% support2) ~ h3wp34,
                                     !(h3wp34 %in% support2) & !(h3wp22 %in% support2) & (h3wp48 %in% support2) ~ h3wp48,
                                     TRUE ~ 9999),
           father_support = case_when(h3wp26 %in% support ~ h3wp26,
                                     h3wp40 %in% support & !(h3wp26 %in% support) ~ h3wp40,
                                     !(h3wp40 %in% support) & !(h3wp26 %in% support) & (h3wp54 %in% support) ~ h3wp54,
                                     TRUE ~ 9999),
           father_support2 = case_when(h3wp27 %in% support2 ~ h3wp27,
                                     h3wp41 %in% support2 & !(h3wp27 %in% support2) ~ h3wp41,
                                     !(h3wp41 %in% support2) & !(h3wp27 %in% support2) & (h3wp55 %in% support2) ~ h3wp55,
                                     TRUE ~ 9999),
           mother_warmth = case_when(h3wp19 %in% valid_vars ~ h3wp19,
                                     h3wp31 %in% valid_vars & !(h3wp19 %in% valid_vars) ~ h3wp31,
                                     !(h3wp31 %in% valid_vars) & !(h3wp19 %in% valid_vars) & (h3wp45 %in% valid_vars) ~ h3wp45,
                                     !(h3wp31 %in% valid_vars) & !(h3wp19 %in% valid_vars) & !(h3wp45 %in% valid_vars) & (h3wp63 %in% valid_vars) ~ h3wp63,
                                     TRUE ~ 9999),
           father_warmth = case_when(h3wp24 %in% valid_vars ~ h3wp24,
                                     h3wp38 %in% valid_vars & !(h3wp24 %in% valid_vars) ~ h3wp38,
                                     !(h3wp38 %in% valid_vars) & !(h3wp24 %in% valid_vars) & (h3wp52 %in% valid_vars) ~ h3wp52,
                                     TRUE ~ 9999),
           h3ws5a = ifelse(!(h3ws5a %in% sibling_valid), NA, h3ws5a),
           h3ws5b = ifelse(!(h3ws5b %in% sibling_valid), NA, h3ws5b),
           h3ws5c = ifelse(!(h3ws5c %in% sibling_valid), NA, h3ws5c),
           h3ws5d = ifelse(!(h3ws5d %in% sibling_valid), NA, h3ws5d),
           h3ws6a = ifelse(!(h3ws6a %in% sibling_valid), NA, h3ws6a),
           h3ws6b = ifelse(!(h3ws6b %in% sibling_valid), NA, h3ws6b),
           h3ws6c = ifelse(!(h3ws6c %in% sibling_valid), NA, h3ws6c),
           h3ws6d = ifelse(!(h3ws6d %in% sibling_valid), NA, h3ws6d)) %>%
    mutate(sibling_closeness = rowMeans(subset(df, select = (c(h3ws5a, h3ws5b, h3ws5c, h3ws5d))), na.rm = TRUE),
           sibling_support = rowMeans(subset(df, select = (c(h3ws6a, h3ws6b, h3ws6c, h3ws6d))), na.rm = TRUE)
           ) 
  
  return(df)
}

w3_family <- c("h3wp20", "h3wp32", "h3wp46", "h3wp64", "h3wp21", "h3wp22", "h3wp33", "h3wp34", "h3wp47", "h3wp48", "h3wp65", "h3wp25", "h3wp39", "h3wp53", "h3wp26", "h3wp27", "h3wp40", "h3wp41", "h3wp54", "h3wp55", "h3wp19", "h3wp31", "h3wp45", "h3wp63", "h3wp24", "h3wp38", "h3wp52", "h3ws5a", "h3ws5b", "h3ws5c", "h3ws5d", "h3ws6a", "h3ws6b", "h3ws6c", "h3ws6d", "h3ma4", "h3ma3", "h3ma5", "h3ma6")

w3_structure <- c("h3cj160")

w3_partner <- c("h3mr1", "h3mr3_a", "h3mr6_a", "h3mr3_b", "h3mr6_b", "h3bm2")

w3_child <- c("h3mac10")

w3_education <- c("h3ed1", "h3ed19", "h3ed20", "h3ed27", "h3ed29", "h3ed30", "h3ed16", "h3ed17")

w3_poverty <- c("h3ed1c", "h3ed1d", "h3ec1e", "h3ec3", "h3ec4", "h3ec5", "h3ec6", "h3ec7", "h3ec9")

add_w3_employ<- function(df){
  #df : joined waves input
  #return : new data frame that includes truncated industry codes
  #truncates values in h3lm25 by keeping first 2 digits
  df %>% 
    mutate(industry_code = substr(h3lm25, 1,2))
  
  return(df)
}

w3_employ <- c("h3lm25", "h3lm27")

w3_prospects <- c("h3ec59", "h3ec30")

w3_ses <- c(w3_education, w3_poverty, w3_employ, w3_prospects)

w3_ind_vars <- c(w3_health, w3_social, w3_prosocial, w3_peer, w3_religion, w3_family, w3_structure, w3_partner, w3_child, w3_ses)
```

```{r wave 4}
w4_health <- c("h4to3", "h4to6", "h4id7", "h4id9c", "h4gh8", "h4gh9", "h4gh1", "h4hs3")

w4_social <- c("h4ws4")

w4_prosocial <- c("h4da26", "h4da27")

w4_peer <- c("h4se4", "h4se5")

w4_religion <- c("h4re7", "h4re8", "h4re9", "h4re11")

w4_family <- c("h4wp24", "h4wp25", "h4wp38", "h4wp39", "h4wp23", "h4wp37", "h4ma1", "h4ma3", "h4ma5")

w4_structure <- c("h4wp3", "h4wp9", "h3wp16", "h3wp30")

w4_partner <- c("h4rd7b", "h4rd7d", "h4rd7e", "h4rd9", "h4rd12", "h4rd14")

w4_child <- c("h4tr9", "h4tr10")

w4_stress <-("h4mh29")

w4_education <- c("h4ed1", "h4ed2", "h4ed8", "h4ed9")

w4_poverty <- c("h4ec1", "h4ec3", "h4ec2")

add_w4_employ<- function(df){
  #df : joined waves input
  #return : new data frame that includes truncated industry codes
  #truncates values in h4lm18 by keeping first 2 digits
  df %>% 
    mutate(industry_code = substr(h4lm18, 1,2))
  
  return(df)
}

w4_employ <- c("h4lm18", "h4lm23", "h4lm14", "h4lm20", "h4lm27")

w4_prospects <- c("h4ec19")

w4_ses <- c(w4_education, w4_poverty, w4_employ, w4_prospects)

w4_ind_vars <- c(w4_health, w4_social, w4_prosocial, w4_peer, w4_religion, w4_family, w4_structure, w4_partner, w4_child, w4_stress, w4_ses)
```

```{r wave 5}
w5_health <- c("h5to1", "h5to3", "h5id4", "h5da2", "h5id21", "h5id22", "h5id1", "h5lm13a", "h5id9")

w5_social <- c("h5ss6", "h5ss1", "h5ss2", "h5ss3a", "h5ss3b", "h5ss3c", "h5ss3d", "h5ss4a", "h5ss4b", "h5ss4c", "h5ss4d", "h5ss5a", "h5ss5b", "h5ss5c", "h5ss5d")

w5_prosocial <- c("h5ss8", "h5ss7")

w5_peer <- c("h5mn11", "h5mn12")

w5_religion <- c("h5re2", "h5re3")

w5_family <- c("h5wp14", "h5wp13", "h5wp28", "h5wp29", "h5wp27")

w5_structure <- c("h5wp15", "h5wp1", "h5wp4", "h5wp18")


add_w5_time <- function(df){
  #combine Y and M columns for h5tr4, h5tr5, h5tr6, h5tr7
  # adds h5tr4_t, h5tr5_t, h5tr6_t, h5tr7_t which combine the number of years and months into total number of months
  df<-df %>% 
    mutate(h5tr4_t = h5tr4y * 12 + h5tr4m, 
           h5tr5_t = h5tr5y * 12 + h5tr5m, 
           h5tr6_t = h5tr6y * 12 + h5tr6m, 
           h5tr7_t = h5tr7y * 12 + h5tr7m) %>%
    select(df, -c(h5tr4m, h5tr4y, h5tr5m, h5tr5y, h5tr6m, h5tr6y, h5tr7m, h5tr7y))
  
  return(df)
}


w5_partner <- c("h5tr1", "h5tr6", "h5tr4", "h5hr1", "h5hr2", "h5tr3", "h5tr4m", "h5tr4y", "h5tr5", "h5tr5m", "h5tr5y", "h5tr6m", "h5tr6y", "h5tr7", "h5tr7m", "h5tr7y")

w5_child <- c("h5se21", "h5se22", "h5se23")

w5_stress <- c("h5mh5a", "h5mh5b", "h5mh5c", "h5mh5d", "h5mh5e", "h5mh6a", "h5mh6b", "h5mh6c", "h5mh6d", "h5mh6e", "h5mh6f","h5mh6g","h5mh6h","h5mh6i","h5mh6j","h5mh6k","h5mh6l","h5mh6m","h5mh6n")

w5_education <- c("h5od10", "h5od11")

w5_poverty <- c("h5ec1", "h5ec4", "h5ec2", "h5ec5a", "h5ec5b", "h5ec5c", "hcec6")

w5_employ <- c("h5lm9", "h5lm10", "h5lm11", "h5lm12", "h5lm15", "h5lm5", "h5lm27")

w5_prospects <- c("h5ec9")

w5_ses <- c(w5_education, w5_poverty, w5_employ, w5_prospects)

w5_ind_vars <- c(w5_health, w5_social, w5_prosocial, w5_peer, w5_religion, w5_family, w5_structure, w5_partner, w5_child, w5_stress, w5_ses)
```


```{r vars by category, all waves}
ind_vars_health <- c(w1_health, w3_health, w4_health, w5_health)

ind_vars_social <- c(w1_social, w3_social, w4_social, w5_social)

ind_vars_prosocial <- c(w3_prosocial, w4_prosocial, w5_prosocial)

ind_vars_peer <- c(w1_peer, w3_peer, w4_peer, w5_peer)

ind_vars_religion <- c(w1_religion, w3_religion, w4_religion, w5_religion)

ind_vars_family <- c(w1_family, w3_family, w4_family, w5_family)

ind_vars_structure <- c(w3_structure, w4_structure, w5_structure)

ind_vars_partner <- c(w3_partner, w4_partner, w5_partner)

ind_vars_child <- c(w3_child , w4_child , w5_child)

ind_vars_stress <- c(w4_stress, w5_stress)

ind_vars_education <- c(w1_education, w3_education, w4_education, w5_education)

ind_vars_poverty <- c(w3_poverty, w4_poverty, w5_poverty)

ind_vars_employ <- c(w3_employ, w4_employ, w5_employ)

ind_vars_prospects <- c(w1_prospects, w3_prospects, w4_prospects, w5_prospects)

ind_vars_ses <- c(ind_vars_education, ind_vars_poverty, ind_vars_employ, ind_vars_prospects)

ind_vars_all <- c(parent_vars, w1_ind_vars, w3_ind_vars, w4_ind_vars, w5_ind_vars)

```



