---
title: "20-explore"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

# Basic Exploration

Exploratory data analysis (an approach to analyzing data sets to summarize their main characteristics, often with visual methods) can be performed here.


```{r load libraries}
# Use pacman, which forces an install if the library isn't present on the running machine
if (!require("pacman"))
  install.packages("pacman")

#pacman::p_install(c(plotly, dotwhisker, broom), force = FALSE)
pacman::p_load(tidyverse, DataExplorer, gridExtra,
               plotly, dotwhisker, broom)
```

```{r generic missing}
graph_missing <- function(df,
                          only_missing = TRUE,
                          title = "Percent Missing", 
                          box_line_size = .3, 
                          label_size = .15, 
                          x_axis_size = 12, 
                          y_axis_size = 12, 
                          title_size = 15){
  # df: data frame to plot missingness
  # only_missing: if set TRUE, then only graph variables with missing values
  # title: graph title
  # box_line_size: size of box-line around percent missing
  # label_size: size of label
  # x_axis_size: font size for x-axis
  # y_axis_size: font size for y-axis
  # title_size = font size for title
  
  if(only_missing == TRUE) {
    df <- df %>% select_if(~sum(is.na(.)) > 0)
    
    plot_missing(data = df,
                 title = title,
                 geom_label_args = list(label.size = box_line_size, 
                                        label.r = unit(0, "lines"),
                                        label.padding = unit(label_size, "lines")),
                 theme_config = list(plot.title = element_text(hjust = 0.5, size = title_size),
                                     axis.text.x = element_text(size = x_axis_size),
                                     axis.text.y = element_text(size = y_axis_size)))
    
  }
  
  else {
    plot_missing(data = df,
                 title = title,
                 geom_label_args = list(label.size = box_line_size, 
                                        label.r = unit(0, "lines"),
                                        label.padding = unit(label_size, "lines")),
                 theme_config = list(plot.title = element_text(hjust = 0.5, size = title_size),
                                     axis.text.x = element_text(size = x_axis_size),
                                     axis.text.y = element_text(size = y_axis_size)))
  }
  
}

# Example
# create random amount of missing data (25% - 75%) in mtcars
# set.seed(42)
# mtcars %>% 
#   map_df(function(z) replace(x = z,
#                              list = sample(x = 1:length(z),
#                                            size = length(z)*runif(1,.25,.75)),
#                              values = NA)) %>% 
#   graph_missing()

```

```{r generic scatterplot}
graph_scatterplot <- function(df, 
                              outcome, 
                              plot_title = "Scatterplots of Variables",
                              opacity = 1,
                              point_color = "black",
                              point_size = 1,
                              num_rows = 3,
                              num_cols = 3,
                              x_axis_size = 12,
                              y_axis_size = 12,
                              title_size = 15){
  # df: data frame to plot
  # plot_title: graph title
  # opacity: How opaque the points should be, scale of 0 to 1
  # point_color: color of the points
  # point_size = size of point
  # num_rows: number of rows for output graphs
  # num_cols: number of columns for outcome graphs
  # x_axis_size: font size for x-axis
  # y_axis_size: font size for y-axis
  
  df %>% 
    plot_scatterplot(by = outcome, 
                     title = plot_title,
                     geom_point_args = list(size = point_size, 
                                            alpha = opacity, 
                                            color = point_color),
                     nrow = num_rows,
                     ncol = num_cols,
                     theme_config = list(plot.title = element_text(hjust = 0.5, size = title_size),
                                         axis.text.x = element_text(size = x_axis_size),
                                         axis.text.y = element_text(size = y_axis_size)))
}
# Example
# mtcars %>% 
#   graph_scatterplot(outcome = "gear", opacity = .5, point_size = 2, point_color = "red", num_rows = 4)
```


```{r generic frequency discrete}
graph_bar_discrete <- function(df,
                               plot_title = "Distributions of Discrete Variables",
                               max_categories = 50,
                               num_rows = 3,
                               num_cols = 3,
                               x_axis_size = 12,
                               y_axis_size = 12,
                               title_size = 15){
  # df: data frame to plot missingness
  # plot_title: Title of plot
  # num_bins: number of bins for the graph
  # num_rows: how many rows to have for output
  # num_cols: how many columns to have for output
  # x_axis_size: font size for x-axis
  # y_axis_size: font size for y-axis
  # title_size: font size for graph title
  
  plot_bar(data = df,
           maxcat = max_categories,
           nrow = num_rows,
           ncol = num_cols,
           title = plot_title,
           theme_config = list(plot.title = element_text(hjust = 0.5, size = title_size),
                               axis.text.x = element_text(size = x_axis_size),
                               axis.text.y = element_text(size = y_axis_size)))
  
}

# # Example 1
# graph_bar_discrete(mtcars, num_rows = 1, num_cols = 2)
# 
# # Example 2
# graph_bar_discrete(mtcars, num_rows = 2, num_cols = 1)
```

```{r generic boxplots}
graph_boxplot <- function(df, 
                          outcome, 
                          plot_title = "Boxplots", 
                          num_rows = 4, 
                          num_cols = 2, 
                          x_axis_size = 12,
                          y_axis_size = 12,
                          title_size = 15){
  # df: data frame
  # outcome: outcome variable
  # plot_title: title of graph. Note that "By <outcome>" is appended
  # num_rows: number of rows for output
  # num_cols: number of columsn for output
  # x_axis_size: size of text for x-axis
  # y_axis_size: size of text for y-axis
  # return: boxplots for covariates
  
  plot_title <- str_c(plot_title, "by", outcome, sep = " ")
  
  df %>% 
    plot_boxplot(by = outcome,
                 title = plot_title,
                 nrow = num_rows,
                 ncol = num_cols,
                 theme_config = list(plot.title = element_text(hjust = 0.5, size = title_size),
                                     axis.text.x = element_text(size = x_axis_size),
                                     axis.text.y = element_text(size = y_axis_size)))
}

# Example 1
# iris %>% graph_boxplot(outcome = "Species")

# Example 2
# mtcars %>% graph_boxplot(outcome = "gear")
```

```{r cramers v function for measure of association}
pairwise_cramers_v <- function(df){
  # df: data frame to use for pairwise cramer's v calculation
  # out: 3 column tibble with all pairwise combos and cramer's v
  
  df_factors <- df %>% dplyr::select_if(is.factor)
  
  df_factors %>%
    as.list() %>%
    expand.grid(var1 = ., var2 = .) %>% 
    mutate(cramer_v = map2_dbl(var1, var2, rcompanion::cramerV, bias.correct = TRUE)) %>% 
    as_tibble() %>% 
    mutate(var1 = expand.grid(names(df_factors), 
                              names(df_factors))[,1],
           var2 = expand.grid(names(df_factors), 
                              names(df_factors))[,2]) %>% 
    dplyr::select(var1, var2, cramer_v)
}

# Example 1
# iris2 <- iris %>%
#   mutate(new1 = as_factor(round(Sepal.Width)),
#          new2 = as_factor(round(Sepal.Length)),
#          new3 = as_factor(round(Petal.Length))) %>%
#   as_tibble()
# 
# iris2 %>%
#   pairwise_cramers_v()
```

```{r better plot cramer v}
plot_cramer_v <- function(df,
                          x_axis_angle = 90, 
                          plot_title = "Association among Categorical Variables",
                          interactive = FALSE){
  # df: output from pairwise_cramers_v function
  # x_axis_angle: angle to write text for x-axis
  # plot_title: title of graph
  # Interactive: Whether to return interactive plot with plotly
  # return: heatmap filled by cramers_v value
  
  # Create n x n matrix for variables using cramer's v
  df_wide <-  df %>% 
    pivot_wider(names_from = var1, values_from = cramer_v)
  
  # make it a matrix but drop first column b/c it's the row names, not a column
  df_matrix <- df_wide %>% dplyr::select(-var2) %>% as.matrix()
  
  # Add row names to matrix 
  dimnames(df_matrix) <- list(df_wide$var2, df_wide$var2)
  
  # graph it
  out <-  df_matrix %>%
    ggcorrplot::ggcorrplot(hc.order = FALSE, 
                           type = "lower",
                           #legend.title = "Cramer's V Statistic",
                           show.legend=FALSE) +
    theme(axis.text.x = element_text(angle = x_axis_angle),
          axis.title = element_blank()) +
    ggtitle(plot_title)
  
  if(interactive){
    plotly::ggplotly(out)
  }
  
  else out
  
}

# Example 1
# iris2 <- iris %>%
#   mutate(new1 = as_factor(round(Sepal.Width)),
#          new2 = as_factor(round(Sepal.Length)),
#          new3 = as_factor(round(Petal.Length))) %>%
#   as_tibble()

# iris2 %>%
#   pairwise_cramers_v() %>%
#   plot_cramer_v(interactive = TRUE)

```

```{r explore affect of joins with logistic regression}
explore_dropped <- function(working_df, 
                            wave_1_data = wave_data[[1]],
                            plot_title = "Affect of Variables on Predicting Being Dropped",
                            color_dot = "yellow",
                            color_line = "light blue",
                            zero_line_color = "light green",
                            size_dot = 2, 
                            size_line = 1){
  # working_df: Data frame to use for further analysis
  # wave_1_data: Data from wave 1
  # return: dot plot for overlapping variables and their affects on predicting whether an aid is missing
  
  # get dropped aids
  aids_dropped <- setdiff(wave_1_data$aid, working_df$aid)
  
  # get variables in both groups
  vars_in_both_waves <- intersect(names(wave_1_data), names(working_df))
  
  # get dataset for regression
  regress_dat <- wave_1_data %>% 
    dplyr::select(all_of(vars_in_both_waves)) %>% 
    mutate(dropped = aid %in% all_of(aids_dropped)) %>% 
    dplyr::select(-aid)
  
  # perform regression and plot it
  glm(dropped ~ ., data = regress_dat) %>% 
    broom::tidy() %>% 
    dotwhisker::dw_plot(dot_args = list(color = color_dot, size = size_dot),
                        whisker_args = list(color = color_line, size = size_line)) +
    ggtitle(plot_title) +
    geom_vline(xintercept = 0, color = zero_line_color) +
    theme_dark() 
}

# Example
# suicide_ds %>% explore_dropped()
```


```{r explore aids not joined}

# This anti_joins specified wave with wave 1 to see what's missing from wave 1
not_in_wave_1 <- function(wave_num, wave_list){
  # wave_num: what wave to anti_join with wave 1
  # wave_list: list containing all waves
  
  out <- anti_join(wave_list[[wave_num]],
                   wave_list[[1]], 
                   by = "aid") %>% nrow()
  return(out)
}


# This anti_joins all two-wave combinations and extracts number of rows
anti_join_2_waves <- function(combos){
  # combos: dataframe of all 2 way combinations for wave numbers
  
  val1 <- combos[1]
  val2 <- combos[2]
  
  out <- reduce(list(wave_data[[val1]],
                     wave_data[[val2]]), 
                .f = anti_join, 
                by = "aid") %>% nrow()
  return(out)
}

# This anti_joins all three-wave combinations and extracts number of rows
anti_join_3_waves <- function(combos){
  # combos: dataframe of all 3 way combinations for wave numbers
  
  val1 <- combos[1]
  val2 <- combos[2]
  val3 <- combos[3]
  
  out <- reduce(list(wave_data[[val1]],
                     wave_data[[val2]], 
                     wave_data[[val3]]), 
                .f = anti_join, 
                by = "aid") %>% nrow()
  return(out)
}

# This anti_joins all four-wave combinations and extracts number of rows
anti_join_4_waves <- function(combos){
  # combos: dataframe of all 4 way combinations for wave numbers
  
  val1 <- combos[1]
  val2 <- combos[2]
  val3 <- combos[3]
  val4 <- combos[4]
  
  out <- reduce(list(wave_data[[val1]], 
                     wave_data[[val2]],
                     wave_data[[val3]], 
                     wave_data[[val4]]), 
                .f = anti_join, 
                by = "aid") %>% nrow()
  return(out)
}

# plotting function for visualizing the anti-joins above
plot_anti_join_waves <- function(dropped_sums){
  # dropped_sums: output from any of the anti-join functions above
  
  dropped_sums %>% 
    pivot_longer(cols = everything(),
                 names_to = "waves",
                 values_to = "total_dropped") %>% 
    ggplot() +
    geom_bar(aes(x = reorder(waves, total_dropped), 
                 y = total_dropped), 
             stat = "identity", fill = "light blue") +
    ggtitle("Total AIDs Dropped") +
    xlab("Wave Combos") +
    ylab("Total Dropped") +
    theme_dark()
}

# Two waves
explore_two_waves <- function(wave_combos){
  # wave_combos: unique wave combinations as list
  
  # get 2-way anti-joins and total dropped from each one
  dropped_2_waves <- wave_combos$two_waves %>%
    map_dfc(anti_join_2_waves)
  
  # rename the list
  names(dropped_2_waves) <- wave_combos$two_waves %>% map_df(str_c, collapse = ",")
  
  # pivot the list and plot
  two_way_plot <- dropped_2_waves %>% plot_anti_join_waves()
  
  return(two_way_plot)
}

# Thre waves
explore_three_waves <- function(wave_combos){
  # wave_combos: unique wave combinations as list
  
  # Get 3-way wave combinations and total dropped
  dropped_3_waves <- wave_combos$three_waves %>%
    map_dfc(anti_join_3_waves)
  
  # rename the list
  names(dropped_3_waves) <- wave_combos$three_waves %>% map_df(str_c, collapse = ",")
  
  # plot it
  three_way_plot <- dropped_3_waves %>% plot_anti_join_waves()
  
  return(three_way_plot)
}

# four waves
explore_four_waves <- function(wave_combos){
  # wave_combos: unique wave combinations as list 
  
  # Get 4-way wave combinations and total dropped
  dropped_4_waves <- wave_combos$four_waves %>% 
    map_dfc(anti_join_4_waves)
  
  # rename the list appropriately
  names(dropped_4_waves) <- wave_combos$four_waves %>% map_df(str_c, collapse = ",")
  
  # plot it
  four_way_plot <- dropped_4_waves %>% plot_anti_join_waves()
  
  return(four_way_plot)
  
}

# function used
count_not_joined <- function(wave_data = wave_data, number_waves_joined = 4){
  # wave_data: wave data list from file 10 data read
  # number_waves_joined: Number of joined waves to explore
  
  # Get all wave combinations for sizes 1 - 4 without repeats
  wave_combos <- 2:4 %>% 
    map(gtools::combinations, n = 5, v = 1:5, repeats.allowed = FALSE) %>%
    map(t) %>% 
    map(as_tibble)
  
  # Name the list appropriately
  names(wave_combos) <- c("two_waves", "three_waves", "four_waves")
  
  if(number_waves_joined == 2){
    out <- explore_two_waves(wave_combos = wave_combos)
  }
  
  else if(number_waves_joined == 3){
    out <- explore_three_waves(wave_combos = wave_combos)
  }
  
  else 
    out <- explore_four_waves(wave_combos = wave_combos)
  
  return(out)
  
}
```


```{r explore outcome}

# This function takes a look at the outcome of interest and returns visualization for the counts of different levels within the outcome
explore_outcome <- function(df_raw, df_final, outcome_var){
  # df : working dataframe
  # column : output column name  in string format
  # binary : to indicate if the column is binary or not
  # legit_skip : does the outcome have a level that represents a legit skip
  # skip_var : name of the variable
  
  plot1 <- df_raw %>% 
        dplyr::select(outcome_var) %>% 
        mutate(!!outcome_var := as.factor(.data[[outcome_var]])) %>% #this is because doubles won't be plotted as NA
        group_by(.data[[outcome_var]]) %>% 
        summarize(count = n()) %>% 
        ungroup()  %>% 
        ggplot(aes_string(x = outcome_var, y = "count"))+
        geom_col() +
        theme_minimal() +
        labs(title="Count of Factor Raw Outcome",
             x = outcome_var, y = paste0("Count of ", outcome_var))
  
  warning("The original raw outcome data is displayed by converting it to a factor.  For more information about its actual type, investigate the ds_raw dataframe.  It is most likely a double.")
  
  plot2 <- df_final %>% 
        dplyr::select(outcome_var) %>% 
        group_by(.data[[outcome_var]]) %>% 
        summarize(count = n()) %>% 
        ungroup()  %>% 
        ggplot(aes_string(x = outcome_var, y = "count"))+
        geom_col() +
        theme_minimal() +
        labs(title="Count of Processed Outcome \n(Binarized, NAs Dropped)",
             x = outcome_var, y = paste0("Count of ", outcome_var))
  
  gridExtra::grid.arrange(plot1, plot2, ncol=2)
  
}


# Example
# x <- floor(runif(50, min=0, max=3)) %>% as.data.frame()
# colnames(x) <- "Species"
# x %>% explore_outcome("Species", binary = F, legit_skip = T, skip_var = 2)

```


