---
title: "22-exlore-Outcomes"
output: html_notebook
---

# Outcomes Variables for suicide ideation and marjuana


## Suicide ideation
```{r}
summary(suicidal_id_outcome)
describe(suicidal_id_outcome)
```


## Missing Value Visualization
```{r}

suicidal_id_outcome %>% 
  vis_miss()
```

```{r}
suicidal_id_outcome %>% 
  gg_miss_var(show_pct = T)
```



## Histogram of  Variables

```{r}
suicidal_id_outcome %>%
  dplyr::select(h1su1,h3to130,h4se1) %>% 
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_histogram()
```
```{r}
colnames(suicidal_id_outcome)
```

```{r}

#par(mfrow = c(2,2))
count_response_by_variable <- function(x, ...){
  x %>% group_by_(...) %>% summarise(n = n())
}


par(mfrow = c(2,2))
barplot(count_response_by_variable(suicidal_id_outcome, "h1su1")$n, names.arg = c("0","1","6","8","9"), main = "h1su1")
barplot(count_response_by_variable(suicidal_id_outcome, "h3to130")$n, names.arg = c("0","1","8","7","6","9","missed"), main = "h3to130")
barplot(count_response_by_variable(suicidal_id_outcome, "h4se1")$n, names.arg = c("0","1","6","7","8","missed"), main = "h4se1")
barplot(count_response_by_variable(suicidal_id_outcome, "h5mn8")$n, names.arg = c("0","1","missed"), main = "h5mn8")


```



# Visualization of Suicide

```{r}
suicide_outcome_h1su1 <- suicidal_id_outcome %>% 
  dplyr::select(h1su1)

suicide_outcome_h3to130 <- suicidal_id_outcome %>% 
  dplyr::select(h3to130)

suicide_outcome_h4se1 <- suicidal_id_outcome %>% 
  dplyr::select(h4se1)


suicide_outcome_h1su1 <- data.frame(lapply(suicide_outcome_h1su1, factor, ordered=TRUE, 
                          levels=1:5, 
                          labels=c("0","1","6","8","9")))


suicide_outcome_h3to130 <- data.frame(lapply(suicide_outcome_h3to130, factor, ordered=TRUE, 
                          levels=1:6, 
                          labels=c("0","1","6","7","8","9")))

suicide_outcome_h4se1 <- data.frame(lapply(suicide_outcome_h4se1, factor, ordered=TRUE, 
                          levels=1:5, 
                          labels=c("0","1","6","7","8")))
```



```{r}
plot(likert(suicide_outcome_h1su1),
     type="heat",
           low.color = "white",
           high.color = "blue",
           text.color = "black",
           text.size = 4,
           wrap = 50)

plot(likert(suicide_outcome_h1su1),
     type="density",
           facet = TRUE,
           bw = 0.5)
```






## Marijuana
```{r}
summary(marijuana_outcome_usage30)
describe(marijuana_outcome_usage30)
```
