---
title: "31-rescale-wave5"
output: html_notebook
---


Problem here is that if changing the wave 5 data set, some variables have 5 unique number, however, they are not 1 to 4, so need to specify one by one.

h5id6g and h5id6i: 0 1 NA
h5ss0a, h5ss0b, h5ss0c and h5ss0d: 1 2 3 4 NA
h5pe1, h5pe2 and h5pe3: 1 2 3 4 5 NA

```{r}
str(wave5)
rapply(wave5,function(x)length(unique(x)))

unique(wave5$H5HR5L)


change_scale <- function(df, col_name){

  for (i in 1:nrow(df)){
    if (is.null(df$col_name[i])){
      print("is na")
    }
    else if (df$col_name[i]== 1){
      df$col_name[i]= 0
      print("hi")
    }
    else if (df$col_name[i]== 2){
      df$col_name[i]= 1
    }
    else if (df$col_name[i]== 3){
      df$col_name[i]= 2
    }
    else if(df$col_name[i]== 4){
      df$col_name[i]= 3
    }
    
  }
  
  #return(df)
}

```



Test on generated data
```{r}
employee <- c('John', 'Doe','Peter', 'Gynn','Jolie', 'Hope', 'Aoe')
salary <- c(1, 2, 1,NA,3,NA,4)
startdate <- as.Date(c('2010-11-1',NA,'2007-3-14','2007-3-14','2007-3-14','2007-3-14','2007-3-14'))

employ.data <- data.frame(employee, salary, startdate)
employ.data

change_scale <- function(df, col_name){

  for (i in 1:nrow(df)){
    if (is.null(df$col_name[i])){
      print("is na")
    }
    else if (df$col_name[i]== 1){
      df$col_name[i]= 0
      print("hi")
    }
    else if (df$col_name[i]== 2){
      df$col_name[i]= 1
    }
    else if (df$col_name[i]== 3){
      df$col_name[i]= 2
    }
    else if(df$col_name[i]== 4){
      df$col_name[i]= 3
    }
    
  }
  
  #return(df)
}

change_scale(employ.data,salary)


employ.data


length(employ.data$salary[4])
```

