---
title: "96-outcome-coefficients"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r source files, include=FALSE}
source("function_import.R")
```

```{r load libraries, include=FALSE}
# Use pacman, which forces an install if the library isn't present on the running machine
if (!require("pacman")) install.packages("pacman")
#pacman::p_install(plotly)
pacman::p_load(tidyverse, h2o, furrr)

```

```{r initializations, include=FALSE}
port_no <- start_h2o()
h2o.no_progress()
future::plan(multiprocess)
```


```{r}
library(ggplot2)
library(ROCR)
```

```{r}
load_from_csv <- function(read_var, read_dir = '.', notasks = NULL, best_ind = NULL){
  #Function load_from_csv: loads dataframes from 'read_dir/[read_var]_[1:notasks].csv
  #read_var: variable name, usually what the data is saved under
  #read_dir (default '.'): string reflecting base directory;
  #notasks: total number of processes that have this file
  #best_ind: specific process index to read.  If specified, `notasks` is ignored.
  #Returns: the generated dataframe from all processes
  
  #get variable name as string
  read_var_str <- deparse(substitute(read_var))
  print(read_var_str)
  
  if(!is.null(best_ind))
    inds_to_read = best_ind
  else{
    if(length(notasks)==1){
      inds_to_read <- seq(1, notasks)
      print(inds_to_read)
    }
    else{
      inds_to_read <- notasks
      print(inds_to_read)
    }
  }
  
  #generate file strings
  read_fnames <- str_c(read_dir, str_c('/', read_var_str, '_', inds_to_read, '.csv'))
  print(read_fnames)
  
  #read the csvs
  read_data <- map_dfr(read_fnames, read_csv)
  
  #return the data
  return(read_data)
}

```

#Overall ranking from 2 outcomes
prob_drink
```{r seeds for reproducibility}
outcome = 'prob_drink'
fbase = '/scratch/p_gaydosh_dsi/DSI/'
results_directory <- str_c(fbase, outcome, '/results_run_1108')
no_tasks <- get_good_task_ids(results_directory)
```


```{r compute/save or load bs rf model permutation, include=FALSE}

bs_rf_perm_plt <- NULL
  
# get data files
bs_rf_perm_plt <- load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

```


```{r aggregate rf perm results}
met <- 'pr_auc'
bs_rf_perm <- bs_rf_perm_plt %>%
  get_permute_placement(metric_oi=met) %>%
  add_attribute_names('predictor', full_dataset) %>%
  dplyr::select(predictor, everything())

bs_rf_perm
```


```{r}
bs_rf_perm_probdrink <- bs_rf_perm %>%
  select(predictor, overall_rank) %>%
  rename(variable = predictor)
```

```{r}
bs_rf_perm_probdrink
```


hv_drink
```{r seeds for reproducibility}
outcome = 'hv_drink'
results_directory <- str_c(fbase, outcome, '/results_full_h2o_2')
no_tasks <- get_good_task_ids(results_directory)
```


```{r compute/save or load bs rf model permutation, include=FALSE}

bs_rf_perm_plt <- NULL
  
# get data files
bs_rf_perm_plt <- load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

```


```{r aggregate rf perm results}
met <- 'pr_auc'
bs_rf_perm <- bs_rf_perm_plt %>%
  get_permute_placement(metric_oi=met) %>%
  add_attribute_names('predictor', full_dataset) %>%
  dplyr::select(predictor, everything())

bs_rf_perm
```


```{r}
bs_rf_perm_hvdrink <- bs_rf_perm %>%
  select(predictor, overall_rank) %>%
  rename(variable = predictor)
```

```{r}
bs_rf_perm_hvdrink
```


#combine data
```{r}
bs_rf_perm_probdrink_long <- bs_rf_perm_probdrink %>%
  rename(prob_drink = overall_rank)

bs_rf_perm_probdrink_long
```


```{r}
bs_rf_perm_hvdrink_long <- bs_rf_perm_hvdrink %>%
  rename(heavy_drink = overall_rank)

bs_rf_perm_hvdrink_long
```


```{r}
bs_rf_perm_joined_for_graph <- bs_rf_perm_hvdrink_long %>%
  left_join(bs_rf_perm_probdrink_long)

bs_rf_perm_joined_for_graph
```


#plot
```{r}
qplot(data=bs_rf_perm_hvdrink_long, colour = as.factor(heavy_drink), y=variable)
```

```{r}
bs_rf_perm_hvdrink_long$heavy_drink <- as.character(bs_rf_perm_hvdrink_long$heavy_drink)

ggplot(bs_rf_perm_hvdrink_long,
       aes(x=heavy_drink,y=variable,colour=heavy_drink)) +
  geom_point(position=position_jitter(width=0.1,height=0))
```

