---
title: "93-check-lasso-bug"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r source files, include=FALSE}
source("function_import.R")
```

```{r load libraries, include=FALSE}
# Use pacman, which forces an install if the library isn't present on the running machine
if (!require("pacman")) install.packages("pacman")
#pacman::p_install(plotly)
pacman::p_load(tidyverse, h2o, furrr)

```

```{r initializations, include=FALSE}
port_no <- start_h2o()
h2o.no_progress()
future::plan(multiprocess)
```


```{r}
library(ggplot2)
library(ROCR)
```



#feature distribution across bootstrap

```{r}
load_from_csv <- function(read_var, read_dir = '.', notasks = NULL, best_ind = NULL){
  #Function load_from_csv: loads dataframes from 'read_dir/[read_var]_[1:notasks].csv
  #read_var: variable name, usually what the data is saved under
  #read_dir (default '.'): string reflecting base directory;
  #notasks: total number of processes that have this file
  #best_ind: specific process index to read.  If specified, `notasks` is ignored.
  #Returns: the generated dataframe from all processes
  
  #get variable name as string
  read_var_str <- deparse(substitute(read_var))
  print(read_var_str)
  
  if(!is.null(best_ind))
    inds_to_read = best_ind
  else{
    if(length(notasks)==1){
      inds_to_read <- seq(1, notasks)
      print(inds_to_read)
    }
    else{
      inds_to_read <- notasks
      print(inds_to_read)
    }
  }
  
  #generate file strings
  read_fnames <- str_c(read_dir, str_c('/', read_var_str, '_', inds_to_read, '.csv'))
  print(read_fnames)
  
  #read the csvs
  read_data <- map_dfr(read_fnames, read_csv)
  
  #return the data
  return(read_data)
}

```


```{r seeds for reproducibility}
outcome = 'prob_drink'
fbase = '/scratch/p_gaydosh_dsi/DSI/'
results_directory <- str_c(fbase, outcome, '/results_run_0316_25')
```

```{r}

  ran_files_pdrink <- list.files(results_directory)
  
  map(ran_files_pdrink, ~str_extract(., "\\d+")) %>%
    unlist() %>%
    tibble() %>%
    rename(ids='.') %>%
    group_by(ids) %>%
    summarise(counts=n(), .groups='drop_last') %>%
    filter(counts==max(counts)) %>%
    slice(c(1:20)) %>%
    pull(ids)
```

```{r}
no_tasks <- get_good_task_ids(results_directory)
```

```{r compute/save or load bs lasso model permutation, include=FALSE}

bs_lasso_perm_plt = NULL
  
# get data files
bs_lasso_perm_plt = load_from_csv(bs_lasso_perm_plt, results_directory, no_tasks)

```

```{r}
bs_lasso_perm_plt
```
```{r}
bs_lasso_perm_plt %>%
  filter(accuracy!=0)
```



```{r}
summary(bs_lasso_perm_plt)
```


```{r compute/save or load bs lasso model permutation, include=FALSE}

bs_lasso_seeds = NULL
  
# get data files
bs_lasso_seeds = load_from_csv(bs_lasso_seeds, results_directory, no_tasks)

```


```{r}
bs_lasso_seeds
```

