---
title: "h2o-credentials"
output: html_document
editor_options: 
  chunk_output_type: console
---

Run this notebook to correctly generate your private h2o credentials.  You can either run this locally and then more the two files generated over to ACCRE _in_ your despair directory, or you can put this file in your despair directory and then run it. 

**Don't commit this file to the repository.**

**Make sure to change the seed to something a number strange and outrageous!**

```{r load libraries}
library(pacman)
pacman::p_load(stringi, stringr)
```

```{r}
set.seed(0) #change this number to something outlandish and wild!
my_id <- 'bell' #change this to reflect something about you!
```

```{r}
no_chars <- 43
outvar1 <- stringi::stri_rand_strings(1, no_chars)
outvar2 <- str_c(my_id, '_', stringi::stri_rand_strings(1, no_chars))
```

```{r}
realm_text <- str_c(outvar1, ':', outvar2)
config_text <- str_c('init.username=', outvar1, '\n', 'init.password=', outvar2, '\n')
```

```{r}
write(realm_text, 'realm.properties')
write(config_text, '.h2oconfig')
```











