---
title: "97-check-overlap"
output: html_document
---

1. verify the first 20 for different outcomes
```{r}
overall_rank_20_prob_drink <- bs_rf_perm_20_variable
overall_rank_20_prob_drink
```


try other outcomes:

all_outcomes = c("i_drug", "hv_drink", "p_drug", "prob_drink")
binarize= FALSE
all_results_directory = c("/results_full_h2o_2", "/results_full_h2o_2", "/results_full_h2o_2_tsunk", "/results_run_1108")


prob_drink

```{r seeds for reproducibility}
outcome = 'prob_drink'
results_directory <- str_c(fbase, outcome, '/results_run_1108')
```

```{r}
no_tasks <- get_good_task_ids(results_directory)

bs_rf_perm_plt_probdrink = NULL

# get data files
bs_rf_perm_plt_probdrink = load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

bs_rf_perm_plt_probdrink
```


```{r}
bs_rf_perm_20_variable_probdrink <- bs_rf_perm_plt_probdrink %>%
  get_permute_placement(metric_oi=met) %>%
  top_n(20) %>%
  select(predictor) %>%
  rename(variable=predictor)


overall_rank_20_prob_drink <- bs_rf_perm_20_variable_probdrink
```



i_drug
```{r seeds for reproducibility}
outcome = 'i_drug'
results_directory <- str_c(fbase, outcome, '/results_full_h2o_2')
```

```{r}
no_tasks <- get_good_task_ids(results_directory)

bs_rf_perm_plt_idrug = NULL

# get data files
bs_rf_perm_plt_idrug = load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

bs_rf_perm_plt_idrug
```


```{r}
bs_rf_perm_20_variable_idrug <- bs_rf_perm_plt_idrug %>%
  get_permute_placement(metric_oi=met) %>%
  top_n(20) %>%
  select(predictor) %>%
  rename(variable=predictor)


overall_rank_20_idrug <- bs_rf_perm_20_variable_idrug
```



hv_drink
```{r seeds for reproducibility}
outcome = 'hv_drink'
results_directory <- str_c(fbase, outcome, '/results_full_h2o_2')
```

```{r}
no_tasks <- get_good_task_ids(results_directory)

bs_rf_perm_plt_hvdrink = NULL

# get data files
bs_rf_perm_plt_hvdrink = load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

bs_rf_perm_plt_hvdrink
```


```{r}
bs_rf_perm_20_variable_hvdrink <- bs_rf_perm_plt_hvdrink %>%
  get_permute_placement(metric_oi=met) %>%
  top_n(20) %>%
  select(predictor) %>%
  rename(variable=predictor)


overall_rank_20_hvdrink <- bs_rf_perm_20_variable_hvdrink
```



p_drug
```{r seeds for reproducibility}
outcome = 'p_drug'
results_directory <- str_c(fbase, outcome, '/results_full_h2o_2_tsunk')
```

```{r}
no_tasks <- get_good_task_ids(results_directory)

bs_rf_perm_plt_pdrug = NULL

# get data files
bs_rf_perm_plt_pdrug = load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

bs_rf_perm_plt_pdrug
```


```{r}
bs_rf_perm_20_variable_pdrug <- bs_rf_perm_plt_pdrug %>%
  get_permute_placement(metric_oi=met) %>%
  top_n(20) %>%
  select(predictor) %>%
  rename(variable=predictor)


overall_rank_20_pdrug <- bs_rf_perm_20_variable_pdrug
```





```{r}
overall_rank_20_prob_drink
overall_rank_20_pdrug
overall_rank_20_idrug
overall_rank_20_hvdrink
```
```{r}
paste0(round(100*length(intersect(overall_rank_20_prob_drink$variable, overall_rank_20_pdrug$variable))/nrow(overall_rank_20_prob_drink)), "%")
paste0(round(100*length(intersect(overall_rank_20_prob_drink$variable, overall_rank_20_idrug$variable))/nrow(overall_rank_20_prob_drink)), "%")
paste0(round(100*length(intersect(overall_rank_20_prob_drink$variable, overall_rank_20_hvdrink$variable))/nrow(overall_rank_20_prob_drink)), "%")
```

```{r}
paste0(round(100*length(intersect(overall_rank_20_pdrug$variable, overall_rank_20_idrug$variable))/nrow(overall_rank_20_pdrug)), "%")
paste0(round(100*length(intersect(overall_rank_20_pdrug$variable, overall_rank_20_hvdrink$variable))/nrow(overall_rank_20_pdrug)), "%")
```

```{r}
paste0(round(100*length(intersect(overall_rank_20_idrug$variable, overall_rank_20_hvdrink$variable))/nrow(overall_rank_20_idrug)), "%")
```




try for the first 10

prob_drink

```{r seeds for reproducibility}
outcome = 'prob_drink'
results_directory <- str_c(fbase, outcome, '/results_run_1108')
```

```{r}
no_tasks <- get_good_task_ids(results_directory)

bs_rf_perm_plt_probdrink = NULL

# get data files
bs_rf_perm_plt_probdrink = load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

bs_rf_perm_plt_probdrink
```


```{r}
overall_rank_10_prob_drink <- bs_rf_perm_plt_probdrink %>%
  get_permute_placement(metric_oi=met) %>%
  top_n(10) %>%
  select(predictor) %>%
  rename(variable=predictor)

```



i_drug
```{r seeds for reproducibility}
outcome = 'i_drug'
results_directory <- str_c(fbase, outcome, '/results_full_h2o_2')
```

```{r}
no_tasks <- get_good_task_ids(results_directory)

bs_rf_perm_plt_idrug = NULL

# get data files
bs_rf_perm_plt_idrug = load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

bs_rf_perm_plt_idrug
```


```{r}
bs_rf_perm_10_variable_idrug <- bs_rf_perm_plt_idrug %>%
  get_permute_placement(metric_oi=met) %>%
  top_n(10) %>%
  select(predictor) %>%
  rename(variable=predictor)


overall_rank_10_idrug <- bs_rf_perm_10_variable_idrug
```



hv_drink
```{r seeds for reproducibility}
outcome = 'hv_drink'
results_directory <- str_c(fbase, outcome, '/results_full_h2o_2')
```

```{r}
no_tasks <- get_good_task_ids(results_directory)

bs_rf_perm_plt_hvdrink = NULL

# get data files
bs_rf_perm_plt_hvdrink = load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

bs_rf_perm_plt_hvdrink
```


```{r}
bs_rf_perm_10_variable_hvdrink <- bs_rf_perm_plt_hvdrink %>%
  get_permute_placement(metric_oi=met) %>%
  top_n(10) %>%
  select(predictor) %>%
  rename(variable=predictor)


overall_rank_10_hvdrink <- bs_rf_perm_10_variable_hvdrink
```



p_drug
```{r seeds for reproducibility}
outcome = 'p_drug'
results_directory <- str_c(fbase, outcome, '/results_full_h2o_2_tsunk')
```

```{r}
no_tasks <- get_good_task_ids(results_directory)

bs_rf_perm_plt_pdrug = NULL

# get data files
bs_rf_perm_plt_pdrug = load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

bs_rf_perm_plt_pdrug
```


```{r}
bs_rf_perm_10_variable_pdrug <- bs_rf_perm_plt_pdrug %>%
  get_permute_placement(metric_oi=met) %>%
  top_n(10) %>%
  select(predictor) %>%
  rename(variable=predictor)


overall_rank_10_pdrug <- bs_rf_perm_10_variable_pdrug
```





```{r}
overall_rank_10_prob_drink
overall_rank_10_pdrug
overall_rank_10_idrug
overall_rank_10_hvdrink
```

```{r}
paste0(round(100*length(intersect(overall_rank_10_prob_drink$variable, overall_rank_10_pdrug$variable))/nrow(overall_rank_10_prob_drink)), "%")
paste0(round(100*length(intersect(overall_rank_10_prob_drink$variable, overall_rank_10_idrug$variable))/nrow(overall_rank_10_prob_drink)), "%")
paste0(round(100*length(intersect(overall_rank_10_prob_drink$variable, overall_rank_10_hvdrink$variable))/nrow(overall_rank_10_prob_drink)), "%")
```

```{r}
paste0(round(100*length(intersect(overall_rank_10_pdrug$variable, overall_rank_10_idrug$variable))/nrow(overall_rank_10_pdrug)), "%")
paste0(round(100*length(intersect(overall_rank_10_pdrug$variable, overall_rank_10_hvdrink$variable))/nrow(overall_rank_10_pdrug)), "%")
```

```{r}
paste0(round(100*length(intersect(overall_rank_10_idrug$variable, overall_rank_10_hvdrink$variable))/nrow(overall_rank_10_idrug)), "%")
```




try the first 50

prob_drink

```{r seeds for reproducibility}
outcome = 'prob_drink'
results_directory <- str_c(fbase, outcome, '/results_run_1108')
```

```{r}
no_tasks <- get_good_task_ids(results_directory)

bs_rf_perm_plt_probdrink = NULL

# get data files
bs_rf_perm_plt_probdrink = load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

bs_rf_perm_plt_probdrink
```


```{r}
overall_rank_50_prob_drink <- bs_rf_perm_plt_probdrink %>%
  get_permute_placement(metric_oi=met) %>%
  top_n(50) %>%
  select(predictor) %>%
  rename(variable=predictor)

```



i_drug
```{r seeds for reproducibility}
outcome = 'i_drug'
results_directory <- str_c(fbase, outcome, '/results_full_h2o_2')
```

```{r}
no_tasks <- get_good_task_ids(results_directory)

bs_rf_perm_plt_idrug = NULL

# get data files
bs_rf_perm_plt_idrug = load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

bs_rf_perm_plt_idrug
```


```{r}
overall_rank_50_idrug <- bs_rf_perm_plt_idrug %>%
  get_permute_placement(metric_oi=met) %>%
  top_n(50) %>%
  select(predictor) %>%
  rename(variable=predictor)

```



hv_drink
```{r seeds for reproducibility}
outcome = 'hv_drink'
results_directory <- str_c(fbase, outcome, '/results_full_h2o_2')
```

```{r}
no_tasks <- get_good_task_ids(results_directory)

bs_rf_perm_plt_hvdrink = NULL

# get data files
bs_rf_perm_plt_hvdrink = load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

bs_rf_perm_plt_hvdrink
```


```{r}
overall_rank_50_hvdrink <- bs_rf_perm_plt_hvdrink %>%
  get_permute_placement(metric_oi=met) %>%
  top_n(50) %>%
  select(predictor) %>%
  rename(variable=predictor)

```



p_drug
```{r seeds for reproducibility}
outcome = 'p_drug'
results_directory <- str_c(fbase, outcome, '/results_full_h2o_2_tsunk')
```

```{r}
no_tasks <- get_good_task_ids(results_directory)

bs_rf_perm_plt_pdrug = NULL

# get data files
bs_rf_perm_plt_pdrug = load_from_csv(bs_rf_perm_plt, results_directory, no_tasks)

bs_rf_perm_plt_pdrug
```


```{r}
overall_rank_50_pdrug <- bs_rf_perm_plt_pdrug %>%
  get_permute_placement(metric_oi=met) %>%
  top_n(50) %>%
  select(predictor) %>%
  rename(variable=predictor)
```


```{r}
paste0(round(100*length(intersect(overall_rank_50_prob_drink$variable, overall_rank_50_pdrug$variable))/nrow(overall_rank_50_prob_drink)), "%")
paste0(round(100*length(intersect(overall_rank_50_prob_drink$variable, overall_rank_50_idrug$variable))/nrow(overall_rank_50_prob_drink)), "%")
paste0(round(100*length(intersect(overall_rank_50_prob_drink$variable, overall_rank_50_hvdrink$variable))/nrow(overall_rank_50_prob_drink)), "%")
```

```{r}
paste0(round(100*length(intersect(overall_rank_50_pdrug$variable, overall_rank_50_idrug$variable))/nrow(overall_rank_50_pdrug)), "%")
paste0(round(100*length(intersect(overall_rank_50_pdrug$variable, overall_rank_50_hvdrink$variable))/nrow(overall_rank_50_pdrug)), "%")
```

```{r}
paste0(round(100*length(intersect(overall_rank_50_idrug$variable, overall_rank_50_hvdrink$variable))/nrow(overall_rank_50_idrug)), "%")
```